feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 20  # 40
patch_size : 4   # 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
delta_time: 0.0

common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu_raw"

preprocess:
    lidar_type: 2 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
    scan_line: 16 # 16  64  32
    blind: 1 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    # imu to lidar
    extrinsic_T: [0,0,0.03411] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 0, 0, -1,
                   0, -1, 0,
                   -1, 0, 0]



pcd_save:
    pcd_save_en: true

camera:
    img_topic: /cam00/image_raw/compressed
    # imu to camera
    # Rcl: [0.00162756,-0.999991,0.00390957,
    #      -0.0126748,-0.00392989,-0.999912,
    #       0.999918,0.00157786,-0.012681]
    # Pcl: [0.0409257, 0.0318424, -0.0927219]
    # body to image
    extrinsic_T: [0.04323875, -0.13672538, -0.13344563]
    extrinsic_R: [0.00553725,  0.99830489,  0.05793686, 
                 0.99979833, -0.00440848, -0.01959246, 
                -0.01930383,  0.05803366, -0.99812798]