feature_extract_enable : 0
point_filter_num : 1
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 20  # 40
patch_size : 4   # 8
img_enable : 1
lidar_enable : 1
loop_enable : 0
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
delta_time: 0.0
gnss:
    path: "/media/zxq/T5/01graduate/01data/mini/friend_square/rtk/gps_serial_node_2024_04_29_04_37_42.ffp"   # 如果不设置该值就默认从ros包中获取gnss数据
    gnss_en: 1           # 是否使用gnss观测
    extrinsic: [0,-0.120,0.118361]    # Tia a：GNSS接收机 i：imu为中心右前上坐标
    use_ros: 0           # 是否从ros包中获取gnss数据

common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu_raw"

preprocess:
    lidar_type: 2 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
    scan_line: 16 # 16  64  32
    blind: 1 # blind x m disable
    fov: 360  # 视场角
    scan_rang: 1800 # 水平点数
    fov_min: -15
    fov_max: 15

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    # imu to lidar Ril Pil
    extrinsic_T: [0,0,0.03411] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 0, -1, 0,    # 右前上 to lidar
                   1, 0, 0,
                   0, 0, 1]
    # extrinsic_R: [ 0, 0, -1, # imu to lidar
    #                0, -1, 0,
    #                -1, 0, 0]

pcd_save:
    pcd_save_en: true

camera:
    img_topic: /cam00/image_raw/compressed
    # camera to lidar
    Rcl: [0.01930383, -0.99979833, -0.00553725,
         -0.05803366,  0.00440848, -0.99830489,
          0.99812798,  0.01959246, -0.05793686]
    Pcl: [0.13322392, -0.03404434, -0.17242587]
