feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 20  # 40
patch_size : 4   # 8
img_enable : 1 #1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
delta_time: 0.0         # camera与lidar时偏 =lidar时间 - camera时间

gnss:
    gnss_en: 0           # 是否使用gnss观测
    extrinsic: [0,0,0]

common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu/data"
    gnss_topic: "/navsat/fix"

preprocess:
    lidar_type: 2 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
    scan_line: 32 # 16  64  32
    blind: 4 # blind x m disable
    fov: 360  # 视场角
    scan_rang: 3600 # 水平点数
    fov_min: -30
    fov_max: 10

mapping:
    acc_cov_scale: 100    # imu方差
    gyr_cov_scale: 10000
    # imu to lidar
    extrinsic_T: [0,0,0] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: true

camera:
    img_topic: /camera/image_color
    Rcl: [0.999346,  0.032359, -0.0161335,
         -0.0157155, -0.0131319,   -0.99979,
          -0.0325641,    0.99939, -0.0126148]
    Pcl: [-0.0111367, 0.0432606, 0.172745]
