feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 20  # 40
patch_size : 4   # 8
img_enable : 1 #1
lidar_enable : 1
loop_enable : 0
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
delta_time: 0.0         # camera与lidar时偏 =lidar时间 - camera时间

gnss:
    gnss_en: 1           # 是否使用gnss观测
    extrinsic: [0,0,0]
    use_ros: 1

common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu/data"
    gnss_topic: "/navsat/fix"

preprocess:
    lidar_type: 2 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
    scan_line: 32 # 16  64  32
    blind: 4 # blind x m disable
    fov: 360  # 视场角
    scan_rang: 3600 # 水平点数
    fov_min: -30
    fov_max: 10

mapping:
    acc_cov_scale: 100    # imu方差
    gyr_cov_scale: 10000
    # imu to lidar
    extrinsic_T: [0,0,0] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: false

camera:
    img_topic: /camera/image_color
    Rcl: [0.999346,  0.032359, -0.0161335,
         -0.0157155, -0.0131319,   -0.99979,
          -0.0325641,    0.99939, -0.0126148]
    Pcl: [-0.0111367, 0.0432606, 0.172745]

std:
    # pre process
    ds_size: 0.1
    maximum_corner_num: 100

    # key points
    plane_detection_thre: 0.01
    plane_merge_normal_thre: 0.1
    plane_merge_dis_thre: 0.3
    voxel_size: 2
    voxel_init_num: 10
    proj_image_resolution: 0.5
    proj_dis_min: 0
    proj_dis_max: 5
    corner_thre: 10

    # std descriptor
    descriptor_near_num: 20
    descriptor_min_len: 2
    descriptor_max_len: 30
    non_max_suppression_radius: 2
    std_side_resolution: 0.2

    # candidate search
    skip_near_num: 50
    candidate_num: 50
    sub_frame_num: 10
    vertex_diff_threshold: 0.5
    rough_dis_threshold: 0.01
    normal_threshold: 0.2
    dis_threshold: 0.5
    icp_threshold: 0.3

lightglue:
    lightglue_path: /home/zxq/Documents/02base/fastlivo/src/FAST-LIVO-noted/config/weight/superpoint_lightglue.onnx
    extractor_path: /home/zxq/Documents/02base/fastlivo/src/FAST-LIVO-noted/config/weight/superpoint.onnx
    mask_path: /home/zxq/Documents/02base/fastlivo/src/FAST-LIVO-noted/include/LightGlue/mask.jpg